name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Config 
      id: cfg
      run: |
        echo PATH:${PATH}
        KK="this is KK $(date)"
        echo "${KK}"

        echo "::set-env name=KK::${KK}"
        echo "::set-output name=kk::${KK}"
        echo "::set-output name=flag::no"
        echo "::add-path::${GITHUB_WORKSPACE}/.github/workflows/bin"

    - name: Work Step
      run: |
        echo "Env variable KK: __${KK}__"
        echo "Output variable kk: __${{ steps.cfg.outputs.kk }}__"
        echo PATH: ${PATH}
        kk-test.sh a1 a2 a3 ${KK}

    - name: Skip Step
      run: |
        echo Did't skip?
      if: ${{ steps.cfg.outputs.flag }} == yes

    - name: Env Dump
      run: |
        echo PATH:${PATH}
        env | grep GITHUB_
        echo ==============
        echo ${GITHUB_EVENT_PATH}
        cat ${GITHUB_EVENT_PATH}
        echo 
        echo ==============
        env
