name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Config 
      id: cfg
      run: |
        KK="this is KK $(date)"
        echo ::set-env name=KK::${KK}
        echo ::set-output name=kk::${KK}

    - name: Work Step
      run: |
        echo "Env variable KK: __${KK}__"
        echo "Output variable kk: __${{ steps.cfg.kk }}__"

